/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package spaceships.view;

import javax.swing.BoxLayout;
import spaceships.SpaceShips;
import spaceships.logic.GraphicsWorld;
import spaceships.logic.PlayField;

/**
 *
 * @author johancarlsson
 */
public class SpaceShipsForm extends javax.swing.JFrame implements IInGameMenuContainer {

    InGameMenuPanel m_InGameMenuPanel;

    /**
     * Creates new form SpaceShipsGameContainer
     */
    public SpaceShipsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_MainLayeredPanel = new javax.swing.JLayeredPane();
        m_SpaceShipPanel = new spaceships.view.SpaceShipPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });

        m_SpaceShipPanel.setLayout(new javax.swing.BoxLayout(m_SpaceShipPanel, javax.swing.BoxLayout.LINE_AXIS));
        m_SpaceShipPanel.setBounds(0, 0, 360, 330);
        m_MainLayeredPanel.add(m_SpaceShipPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(m_MainLayeredPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(m_MainLayeredPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // Resizes the panel to cover the form.
        int width = getContentPane().getWidth();
        int height = getContentPane().getHeight();
        m_MainLayeredPanel.setSize(width, height);
        m_SpaceShipPanel.setSize(width, height);
    }//GEN-LAST:event_formComponentResized

    public void hideInGameMenu() {
        InGameMenuPanel menuPanel = getInGameMenuPanel();
        menuPanel.setVisible(false);

    }

    public void showInGameMenu() {
        SpaceShips.getInstance().setPaused(true);
        InGameMenuPanel menuPanel = getInGameMenuPanel();
        menuPanel.setVisible(true);
        menuPanel.requestFocus();
    }

    public void initializeWorld(GraphicsWorld graphicsWorld) {
        PlayField currentPlayField = new PlayField(500, 500);
        m_SpaceShipPanel.setGraphicsWorld(graphicsWorld);
        m_SpaceShipPanel.setPlayField(currentPlayField);
    }

    public SpaceShipPanel getSpaceShipPanel() {
        return m_SpaceShipPanel;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SpaceShipsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SpaceShipsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SpaceShipsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SpaceShipsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SpaceShipsForm().setVisible(true);
            }
        });
    }

    private InGameMenuPanel getInGameMenuPanel() {
        if (m_InGameMenuPanel == null) {
            String[] options = {"Continue", "Quit"};
            m_InGameMenuPanel = new InGameMenuPanel(options, this);
            m_InGameMenuPanel.setSize(m_InGameMenuPanel.getPreferredSize());
            m_InGameMenuPanel.setLocation((m_SpaceShipPanel.getWidth() - m_InGameMenuPanel.getWidth()) / 2,
                    (m_SpaceShipPanel.getHeight() - m_InGameMenuPanel.getHeight()) / 2);
            m_MainLayeredPanel.add(m_InGameMenuPanel, new Integer(1), 0);

        }
        return m_InGameMenuPanel;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane m_MainLayeredPanel;
    private spaceships.view.SpaceShipPanel m_SpaceShipPanel;
    // End of variables declaration//GEN-END:variables
}
